services:
  - type: web
    name: vidlink-stremio-addon
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: PORT
        value: 10000
